package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/nassiharel/clim/internal/registry"
	"github.com/nassiharel/clim/internal/share"
)

var openYesFlag bool

var openCmd = &cobra.Command{
	Use:   "open <token>",
	Short: "Install tools from a share token",
	Long: `Install tools from a compact share token generated by 'clim share'.

The token encodes a list of tool names. Tools are resolved from your local
catalog and installed via native package managers.

Usage:
  clim open clim:v1:H4sIAAAA...          # interactive: confirm before installing
  clim open clim:v1:H4sIAAAA... --yes    # non-interactive: install all`,
	Args: cobra.ExactArgs(1),
	RunE: runOpen,
}

func init() {
	openCmd.Flags().BoolVarP(&openYesFlag, "yes", "y", false, "Install all tools without prompting")
	rootCmd.AddCommand(openCmd)
}

func runOpen(cmd *cobra.Command, args []string) error {
	token := args[0]

	// Decode the share token.
	names, err := share.Decode(token)
	if err != nil {
		return fmt.Errorf("invalid share token: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Share token: %d tools\n", len(names))

	// Load registry and scan PATH.
	regTools, err := svc.ScanOnly(cmd.Context())
	if err != nil {
		return err
	}

	regMap := make(map[string]*registry.Tool, len(regTools))
	for i := range regTools {
		regMap[regTools[i].Name] = &regTools[i]
	}

	// Build install plan.
	ps := buildTokenPlan(names, regMap)

	printPlanSummary(fmt.Sprintf("Share Token Summary — %d tools", len(names)), ps)

	if len(ps.toInstall) == 0 {
		fmt.Fprintln(os.Stderr, "  Nothing to install — all tools are present!")
		return nil
	}

	if !confirmInstall(openYesFlag) {
		fmt.Fprintln(os.Stderr, "  Cancelled.")
		return nil
	}

	succeeded, failed := executeInstalls(ps.toInstall)
	fmt.Fprintf(os.Stderr, "\n──── Done: %d installed, %d failed, %d already present ────\n",
		succeeded, failed, len(ps.alreadyInstalled))
	return nil
}

// buildTokenPlan classifies token tool names into install/skip/error categories.
func buildTokenPlan(names []string, regMap map[string]*registry.Tool) planSummary {
	var ps planSummary

	for _, name := range names {
		rt, exists := regMap[name]
		if !exists {
			ps.unknown = append(ps.unknown, name)
			continue
		}

		if rt.IsInstalled() {
			ps.alreadyInstalled = append(ps.alreadyInstalled, rt.DisplayName)
			continue
		}

		src := rt.Packages.BestInstallSource()
		installArgs := rt.Packages.InstallArgs(src)
		if installArgs == nil {
			ps.noPackage = append(ps.noPackage, name)
			continue
		}

		ps.toInstall = append(ps.toInstall, installPlan{
			name: rt.Name, display: rt.DisplayName,
			cmdArgs: installArgs, source: string(src),
		})
	}

	return ps
}
