name: docker-compose
display_name: Docker Compose
category: Containers
tags:
    - docker
    - container
binary_names:
    - docker-compose
packages:
    choco: docker-compose
    brew: docker-compose
github: docker/compose
