// Package generate produces CI/container configuration files from
// .clim.yaml tool requirements and marketplace package definitions.
package generate

import (
	"fmt"
	"strings"

	"github.com/nassiharel/clim/internal/registry"
	"github.com/nassiharel/clim/internal/teamfile"
)

// Options controls generation behavior.
type Options struct {
	OS          string // ubuntu, debian, alpine, fedora, macos, windows
	BaseImage   string // override default Docker base image
	ProjectName string
}

// ToolInstall holds resolved install info for a single tool.
type ToolInstall struct {
	Name    string
	Version string // constraint from .clim.yaml (e.g. ">=1.28")
	Brew    string
	Apt     string
	Snap    string
	Winget  string
	Choco   string
	Scoop   string
	NPM     string
}

// pmName returns the primary package manager name for the OS.
func pmName(os string) string {
	switch os {
	case "alpine":
		return "apk"
	case "fedora":
		return "dnf"
	case "macos":
		return "brew"
	case "windows":
		return "winget"
	default:
		return "apt-get"
	}
}

// defaultBaseImage returns the default Docker base image for the OS.
func defaultBaseImage(os string) string {
	switch os {
	case "alpine":
		return "alpine:3.20"
	case "fedora":
		return "fedora:41"
	case "debian":
		return "debian:bookworm"
	default:
		return "ubuntu:24.04"
	}
}

// bulkInstallCmd returns the bulk install command for system packages.
func bulkInstallCmd(os string, pkgs []string) string {
	if len(pkgs) == 0 {
		return ""
	}
	switch os {
	case "alpine":
		return "apk add --no-cache " + strings.Join(pkgs, " ")
	case "fedora":
		return "dnf install -y " + strings.Join(pkgs, " ")
	default: // ubuntu, debian
		return "sudo apt-get update && sudo apt-get install -y " + strings.Join(pkgs, " ")
	}
}

// ResolveInstalls maps .clim.yaml tools to their package IDs from the catalog.
func ResolveInstalls(tf *teamfile.TeamFile, catalog []registry.Tool) []ToolInstall {
	toolMap := make(map[string]*registry.Tool, len(catalog))
	for i := range catalog {
		toolMap[catalog[i].Name] = &catalog[i]
	}

	allRequired := append(tf.Tools, tf.Optional...)
	var installs []ToolInstall

	for _, req := range allRequired {
		t, ok := toolMap[req.Name]
		if !ok {
			installs = append(installs, ToolInstall{Name: req.Name, Version: req.Version})
			continue
		}
		installs = append(installs, ToolInstall{
			Name:    req.Name,
			Version: req.Version,
			Brew:    t.Packages.Brew,
			Apt:     t.Packages.Apt,
			Snap:    t.Packages.Snap,
			Winget:  t.Packages.Winget,
			Choco:   t.Packages.Choco,
			Scoop:   t.Packages.Scoop,
			NPM:     t.Packages.NPM,
		})
	}
	return installs
}

// classifyTools groups tools by install method for the target OS.
func classifyTools(installs []ToolInstall, targetOS string) (sysPkgs, brewPkgs, npmPkgs, wingetPkgs, chopkgs, scoopPkgs, snapPkgs []string) {
	for _, t := range installs {
		switch targetOS {
		case "macos":
			if t.Brew != "" {
				brewPkgs = append(brewPkgs, t.Brew)
			} else if t.NPM != "" {
				npmPkgs = append(npmPkgs, t.NPM)
			}
		case "windows":
			if t.Winget != "" {
				wingetPkgs = append(wingetPkgs, t.Winget)
			} else if t.Choco != "" {
				chopkgs = append(chopkgs, t.Choco)
			} else if t.Scoop != "" {
				scoopPkgs = append(scoopPkgs, t.Scoop)
			} else if t.NPM != "" {
				npmPkgs = append(npmPkgs, t.NPM)
			}
		default: // ubuntu, debian, alpine, fedora
			if t.Apt != "" {
				sysPkgs = append(sysPkgs, t.Apt)
			} else if t.Brew != "" {
				brewPkgs = append(brewPkgs, t.Brew)
			} else if t.Snap != "" {
				snapPkgs = append(snapPkgs, t.Snap)
			} else if t.NPM != "" {
				npmPkgs = append(npmPkgs, t.NPM)
			}
		}
	}
	return
}

// GitHubAction generates a GitHub Actions workflow step for installing tools.
func GitHubAction(installs []ToolInstall, opts Options) string {
	targetOS := opts.OS
	if targetOS == "" {
		targetOS = "ubuntu"
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by clim generate github-action\n")
	b.WriteString(fmt.Sprintf("# Target OS: %s\n", targetOS))
	b.WriteString("# Source: .clim.yaml\n")
	if opts.ProjectName != "" {
		b.WriteString(fmt.Sprintf("# Project: %s\n", opts.ProjectName))
	}
	b.WriteString("\nname: Setup Developer Tools\n\n")
	b.WriteString("on:\n  workflow_call:\n\n")
	b.WriteString("jobs:\n")
	b.WriteString("  setup-tools:\n")

	runner := "ubuntu-latest"
	switch targetOS {
	case "macos":
		runner = "macos-latest"
	case "windows":
		runner = "windows-latest"
	}
	b.WriteString(fmt.Sprintf("    runs-on: %s\n", runner))
	b.WriteString("    steps:\n")
	b.WriteString("      - name: Install developer tools\n")
	b.WriteString("        run: |\n")

	sysPkgs, brewPkgs, npmPkgs, wingetPkgs, _, scoopPkgs, snapPkgs := classifyTools(installs, targetOS)

	if len(sysPkgs) > 0 {
		b.WriteString(fmt.Sprintf("          %s\n", bulkInstallCmd(targetOS, sysPkgs)))
	}
	if len(brewPkgs) > 0 {
		b.WriteString(fmt.Sprintf("          brew install %s\n", strings.Join(brewPkgs, " ")))
	}
	for _, pkg := range wingetPkgs {
		b.WriteString(fmt.Sprintf("          winget install --id %s --accept-source-agreements --accept-package-agreements\n", pkg))
	}
	for _, pkg := range scoopPkgs {
		b.WriteString(fmt.Sprintf("          scoop install %s\n", pkg))
	}
	for _, pkg := range snapPkgs {
		b.WriteString(fmt.Sprintf("          sudo snap install %s\n", pkg))
	}
	if len(npmPkgs) > 0 {
		b.WriteString(fmt.Sprintf("          npm install -g %s\n", strings.Join(npmPkgs, " ")))
	}

	b.WriteString("      - name: Verify tools\n")
	b.WriteString("        run: |\n")
	for _, t := range installs {
		if targetOS == "windows" {
			fmt.Fprintf(&b, "          where %s || echo '%s not found'\n", t.Name, t.Name)
		} else {
			fmt.Fprintf(&b, "          which %s || echo '%s not found'\n", t.Name, t.Name)
		}
	}

	return b.String()
}

// Dockerfile generates a Dockerfile that installs the required tools.
func Dockerfile(installs []ToolInstall, opts Options) string {
	targetOS := opts.OS
	if targetOS == "" {
		targetOS = "ubuntu"
	}
	baseImage := opts.BaseImage
	if baseImage == "" {
		baseImage = defaultBaseImage(targetOS)
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by clim generate dockerfile\n")
	b.WriteString(fmt.Sprintf("# Target OS: %s\n", targetOS))
	b.WriteString("# Source: .clim.yaml\n\n")
	b.WriteString(fmt.Sprintf("FROM %s\n\n", baseImage))

	// Base dependencies.
	switch targetOS {
	case "alpine":
		b.WriteString("RUN apk add --no-cache curl git\n\n")
	case "fedora":
		b.WriteString("RUN dnf install -y curl git && dnf clean all\n\n")
	default:
		b.WriteString("RUN apt-get update && apt-get install -y \\\n")
		b.WriteString("    curl \\\n")
		b.WriteString("    git \\\n")
		b.WriteString("    && rm -rf /var/lib/apt/lists/*\n\n")
	}

	sysPkgs, brewPkgs, npmPkgs, _, _, _, snapPkgs := classifyTools(installs, targetOS)

	if len(sysPkgs) > 0 {
		b.WriteString(fmt.Sprintf("# Tools via %s\n", pmName(targetOS)))
		switch targetOS {
		case "alpine":
			b.WriteString(fmt.Sprintf("RUN apk add --no-cache %s\n\n", strings.Join(sysPkgs, " ")))
		case "fedora":
			b.WriteString(fmt.Sprintf("RUN dnf install -y %s && dnf clean all\n\n", strings.Join(sysPkgs, " ")))
		default:
			b.WriteString("RUN apt-get update && apt-get install -y \\\n")
			for _, pkg := range sysPkgs {
				b.WriteString(fmt.Sprintf("    %s \\\n", pkg))
			}
			b.WriteString("    && rm -rf /var/lib/apt/lists/*\n\n")
		}
	}

	if len(npmPkgs) > 0 {
		b.WriteString("# Tools via npm\n")
		b.WriteString(fmt.Sprintf("RUN npm install -g %s\n\n", strings.Join(npmPkgs, " ")))
	}

	if len(brewPkgs) > 0 {
		b.WriteString("# Tools via brew (requires Homebrew)\n")
		for _, pkg := range brewPkgs {
			b.WriteString(fmt.Sprintf("# RUN brew install %s\n", pkg))
		}
		b.WriteString("\n")
	}

	if len(snapPkgs) > 0 {
		b.WriteString("# Tools via snap\n")
		for _, pkg := range snapPkgs {
			b.WriteString(fmt.Sprintf("# RUN snap install %s\n", pkg))
		}
		b.WriteString("\n")
	}

	b.WriteString("# Verify installations\n")
	b.WriteString("RUN ")
	for i, t := range installs {
		if i > 0 {
			b.WriteString(" && \\\n    ")
		}
		b.WriteString(fmt.Sprintf("which %s", t.Name))
	}
	b.WriteString("\n")

	return b.String()
}

// DevContainer generates a devcontainer.json for VS Code / GitHub Codespaces.
func DevContainer(installs []ToolInstall, opts Options) string {
	projectName := opts.ProjectName
	if projectName == "" {
		projectName = "clim-project"
	}

	var b strings.Builder
	b.WriteString("// Auto-generated by clim generate devcontainer\n")
	b.WriteString("// Source: .clim.yaml\n")
	b.WriteString("{\n")
	b.WriteString(fmt.Sprintf("  \"name\": %q,\n", projectName))
	b.WriteString("  \"image\": \"mcr.microsoft.com/devcontainers/base:ubuntu\",\n")

	var features []string
	var postCreate []string

	for _, t := range installs {
		if feat := devcontainerFeature(t); feat != "" {
			features = append(features, feat)
		} else if t.Apt != "" {
			postCreate = append(postCreate, fmt.Sprintf("sudo apt-get install -y %s", t.Apt))
		} else if t.Brew != "" {
			postCreate = append(postCreate, fmt.Sprintf("brew install %s", t.Brew))
		} else if t.NPM != "" {
			postCreate = append(postCreate, fmt.Sprintf("npm install -g %s", t.NPM))
		}
	}

	if len(features) > 0 {
		b.WriteString("  \"features\": {\n")
		for i, f := range features {
			comma := ","
			if i == len(features)-1 {
				comma = ""
			}
			b.WriteString(fmt.Sprintf("    %s%s\n", f, comma))
		}
		b.WriteString("  },\n")
	}

	if len(postCreate) > 0 {
		b.WriteString("  \"postCreateCommand\": \"")
		b.WriteString(strings.Join(postCreate, " && "))
		b.WriteString("\",\n")
	}

	b.WriteString("  \"customizations\": {\n")
	b.WriteString("    \"vscode\": {\n")
	b.WriteString("      \"settings\": {},\n")
	b.WriteString("      \"extensions\": []\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

// devcontainerFeature maps tool names to known devcontainer features.
func devcontainerFeature(t ToolInstall) string {
	features := map[string]string{
		"kubectl":   "\"ghcr.io/devcontainers/features/kubectl-helm-minikube:1\": { \"helm\": \"none\", \"minikube\": \"none\" }",
		"helm":      "\"ghcr.io/devcontainers/features/kubectl-helm-minikube:1\": { \"kubectl\": \"none\", \"minikube\": \"none\" }",
		"terraform": "\"ghcr.io/devcontainers/features/terraform:1\": {}",
		"docker":    "\"ghcr.io/devcontainers/features/docker-in-docker:2\": {}",
		"node":      "\"ghcr.io/devcontainers/features/node:1\": {}",
		"python":    "\"ghcr.io/devcontainers/features/python:1\": {}",
		"go":        "\"ghcr.io/devcontainers/features/go:1\": {}",
		"rust":      "\"ghcr.io/devcontainers/features/rust:1\": {}",
		"java":      "\"ghcr.io/devcontainers/features/java:1\": {}",
		"dotnet":    "\"ghcr.io/devcontainers/features/dotnet:2\": {}",
		"gh":        "\"ghcr.io/devcontainers/features/github-cli:1\": {}",
		"az":        "\"ghcr.io/devcontainers/features/azure-cli:1\": {}",
		"aws":       "\"ghcr.io/devcontainers/features/aws-cli:1\": {}",
	}
	if f, ok := features[t.Name]; ok {
		return f
	}
	return ""
}
