// Package generate produces CI/container configuration files from
// .clim.yaml tool requirements and marketplace package definitions.
package generate

import (
	"fmt"
	"strings"

	"github.com/nassiharel/clim/internal/registry"
	"github.com/nassiharel/clim/internal/teamfile"
)

// ToolInstall holds resolved install info for a single tool.
type ToolInstall struct {
	Name    string
	Version string // constraint from .clim.yaml (e.g. ">=1.28")
	Brew    string
	Apt     string
	Snap    string
	Winget  string
	Choco   string
	Scoop   string
	NPM     string
}

// ResolveInstalls maps .clim.yaml tools to their package IDs from the catalog.
func ResolveInstalls(tf *teamfile.TeamFile, catalog []registry.Tool) []ToolInstall {
	toolMap := make(map[string]*registry.Tool, len(catalog))
	for i := range catalog {
		toolMap[catalog[i].Name] = &catalog[i]
	}

	allRequired := append(tf.Tools, tf.Optional...)
	var installs []ToolInstall

	for _, req := range allRequired {
		t, ok := toolMap[req.Name]
		if !ok {
			installs = append(installs, ToolInstall{Name: req.Name, Version: req.Version})
			continue
		}
		installs = append(installs, ToolInstall{
			Name:    req.Name,
			Version: req.Version,
			Brew:    t.Packages.Brew,
			Apt:     t.Packages.Apt,
			Snap:    t.Packages.Snap,
			Winget:  t.Packages.Winget,
			Choco:   t.Packages.Choco,
			Scoop:   t.Packages.Scoop,
			NPM:     t.Packages.NPM,
		})
	}
	return installs
}

// GitHubAction generates a GitHub Actions workflow step for installing tools.
func GitHubAction(installs []ToolInstall, projectName string) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by clim generate github-action\n")
	b.WriteString("# Source: .clim.yaml\n")
	if projectName != "" {
		b.WriteString(fmt.Sprintf("# Project: %s\n", projectName))
	}
	b.WriteString("#\n")
	b.WriteString("# Add this as a step in your GitHub Actions workflow:\n")
	b.WriteString("#   - name: Install developer tools\n")
	b.WriteString("#     run: |\n")
	b.WriteString("#       <paste contents below>\n\n")

	b.WriteString("name: Setup Developer Tools\n\n")
	b.WriteString("on:\n  workflow_call:\n\n")
	b.WriteString("jobs:\n")
	b.WriteString("  setup-tools:\n")
	b.WriteString("    runs-on: ubuntu-latest\n")
	b.WriteString("    steps:\n")
	b.WriteString("      - name: Install developer tools\n")
	b.WriteString("        run: |\n")

	// Group by PM for clean output.
	var brewPkgs, aptPkgs, npmPkgs, snapPkgs []string
	for _, t := range installs {
		if t.Brew != "" {
			brewPkgs = append(brewPkgs, t.Brew)
		} else if t.Apt != "" {
			aptPkgs = append(aptPkgs, t.Apt)
		} else if t.Snap != "" {
			snapPkgs = append(snapPkgs, t.Snap)
		} else if t.NPM != "" {
			npmPkgs = append(npmPkgs, t.NPM)
		}
	}

	if len(aptPkgs) > 0 {
		b.WriteString("          sudo apt-get update\n")
		b.WriteString(fmt.Sprintf("          sudo apt-get install -y %s\n", strings.Join(aptPkgs, " ")))
	}
	if len(brewPkgs) > 0 {
		b.WriteString(fmt.Sprintf("          brew install %s\n", strings.Join(brewPkgs, " ")))
	}
	if len(snapPkgs) > 0 {
		for _, s := range snapPkgs {
			b.WriteString(fmt.Sprintf("          sudo snap install %s\n", s))
		}
	}
	if len(npmPkgs) > 0 {
		b.WriteString(fmt.Sprintf("          npm install -g %s\n", strings.Join(npmPkgs, " ")))
	}

	// Add verification step.
	b.WriteString("      - name: Verify tools\n")
	b.WriteString("        run: |\n")
	for _, t := range installs {
		b.WriteString(fmt.Sprintf("          which %s || echo '%s not found'\n", t.Name, t.Name))
	}

	return b.String()
}

// Dockerfile generates a Dockerfile that installs the required tools.
func Dockerfile(installs []ToolInstall, baseImage string) string {
	if baseImage == "" {
		baseImage = "ubuntu:24.04"
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by clim generate dockerfile\n")
	b.WriteString("# Source: .clim.yaml\n\n")
	b.WriteString(fmt.Sprintf("FROM %s\n\n", baseImage))
	b.WriteString("RUN apt-get update && apt-get install -y \\\n")
	b.WriteString("    curl \\\n")
	b.WriteString("    git \\\n")
	b.WriteString("    && rm -rf /var/lib/apt/lists/*\n\n")

	var aptPkgs, brewPkgs, npmPkgs, snapPkgs []string
	for _, t := range installs {
		if t.Apt != "" {
			aptPkgs = append(aptPkgs, t.Apt)
		} else if t.Brew != "" {
			brewPkgs = append(brewPkgs, t.Brew)
		} else if t.NPM != "" {
			npmPkgs = append(npmPkgs, t.NPM)
		} else if t.Snap != "" {
			snapPkgs = append(snapPkgs, t.Snap)
		}
	}

	if len(aptPkgs) > 0 {
		b.WriteString("# Tools available via apt\n")
		b.WriteString("RUN apt-get update && apt-get install -y \\\n")
		for i, pkg := range aptPkgs {
			if i < len(aptPkgs)-1 {
				b.WriteString(fmt.Sprintf("    %s \\\n", pkg))
			} else {
				b.WriteString(fmt.Sprintf("    %s \\\n", pkg))
			}
		}
		b.WriteString("    && rm -rf /var/lib/apt/lists/*\n\n")
	}

	if len(npmPkgs) > 0 {
		b.WriteString("# Tools available via npm\n")
		b.WriteString(fmt.Sprintf("RUN npm install -g %s\n\n", strings.Join(npmPkgs, " ")))
	}

	if len(brewPkgs) > 0 {
		b.WriteString("# Tools available via brew (requires Homebrew)\n")
		for _, pkg := range brewPkgs {
			b.WriteString(fmt.Sprintf("# RUN brew install %s\n", pkg))
		}
		b.WriteString("\n")
	}

	if len(snapPkgs) > 0 {
		b.WriteString("# Tools available via snap\n")
		for _, pkg := range snapPkgs {
			b.WriteString(fmt.Sprintf("# RUN snap install %s\n", pkg))
		}
		b.WriteString("\n")
	}

	// Verification.
	b.WriteString("# Verify installations\n")
	b.WriteString("RUN ")
	for i, t := range installs {
		if i > 0 {
			b.WriteString(" && \\\n    ")
		}
		b.WriteString(fmt.Sprintf("which %s", t.Name))
	}
	b.WriteString("\n")

	return b.String()
}

// DevContainer generates a devcontainer.json for VS Code / GitHub Codespaces.
func DevContainer(installs []ToolInstall, projectName string) string {
	if projectName == "" {
		projectName = "clim-project"
	}

	var b strings.Builder
	b.WriteString("// Auto-generated by clim generate devcontainer\n")
	b.WriteString("// Source: .clim.yaml\n")
	b.WriteString("{\n")
	b.WriteString(fmt.Sprintf("  \"name\": \"%s\",\n", projectName))
	b.WriteString("  \"image\": \"mcr.microsoft.com/devcontainers/base:ubuntu\",\n")

	// Collect features and post-create commands.
	var features []string
	var postCreate []string

	for _, t := range installs {
		// Map known tools to devcontainer features.
		if feat := devcontainerFeature(t); feat != "" {
			features = append(features, feat)
		} else if t.Apt != "" {
			postCreate = append(postCreate, fmt.Sprintf("sudo apt-get install -y %s", t.Apt))
		} else if t.Brew != "" {
			postCreate = append(postCreate, fmt.Sprintf("brew install %s", t.Brew))
		} else if t.NPM != "" {
			postCreate = append(postCreate, fmt.Sprintf("npm install -g %s", t.NPM))
		}
	}

	if len(features) > 0 {
		b.WriteString("  \"features\": {\n")
		for i, f := range features {
			comma := ","
			if i == len(features)-1 {
				comma = ""
			}
			b.WriteString(fmt.Sprintf("    %s%s\n", f, comma))
		}
		b.WriteString("  },\n")
	}

	if len(postCreate) > 0 {
		b.WriteString("  \"postCreateCommand\": \"")
		b.WriteString(strings.Join(postCreate, " && "))
		b.WriteString("\",\n")
	}

	b.WriteString("  \"customizations\": {\n")
	b.WriteString("    \"vscode\": {\n")
	b.WriteString("      \"settings\": {},\n")
	b.WriteString("      \"extensions\": []\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

// devcontainerFeature maps tool names to known devcontainer features.
func devcontainerFeature(t ToolInstall) string {
	features := map[string]string{
		"kubectl":   "\"ghcr.io/devcontainers/features/kubectl-helm-minikube:1\": { \"helm\": \"none\", \"minikube\": \"none\" }",
		"helm":      "\"ghcr.io/devcontainers/features/kubectl-helm-minikube:1\": { \"kubectl\": \"none\", \"minikube\": \"none\" }",
		"terraform": "\"ghcr.io/devcontainers/features/terraform:1\": {}",
		"docker":    "\"ghcr.io/devcontainers/features/docker-in-docker:2\": {}",
		"node":      "\"ghcr.io/devcontainers/features/node:1\": {}",
		"python":    "\"ghcr.io/devcontainers/features/python:1\": {}",
		"go":        "\"ghcr.io/devcontainers/features/go:1\": {}",
		"rust":      "\"ghcr.io/devcontainers/features/rust:1\": {}",
		"java":      "\"ghcr.io/devcontainers/features/java:1\": {}",
		"dotnet":    "\"ghcr.io/devcontainers/features/dotnet:2\": {}",
		"gh":        "\"ghcr.io/devcontainers/features/github-cli:1\": {}",
		"az":        "\"ghcr.io/devcontainers/features/azure-cli:1\": {}",
		"aws":       "\"ghcr.io/devcontainers/features/aws-cli:1\": {}",
	}
	if f, ok := features[t.Name]; ok {
		return f
	}
	return ""
}
