name: Winget

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Winget
    runs-on: windows-latest
    if: "!github.event.release.prerelease"
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: nassiharel.clim
          token: ${{ secrets.WINGET_TOKEN }}
