// assemble-marketplace reads individual tool and pack YAML files from
// marketplace/tools/ and marketplace/packs/, and assembles them into a
// single marketplace.yaml matching the format the CLI expects.
//
// Usage:
//
//	go run ./internal/marketplace/assemble
//	go run ./internal/marketplace/assemble -o marketplace.yaml
//	go run ./internal/marketplace/assemble -dir ./marketplace
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/nassiharel/clim/internal/registry"
)

type assembledFile struct {
	Tools []registry.ToolDef `yaml:"tools"`
	Packs []packDef          `yaml:"packs"`
}

type packDef struct {
	Name        string   `yaml:"name"`
	DisplayName string   `yaml:"display_name"`
	Description string   `yaml:"description,omitempty"`
	Tools       []string `yaml:"tools"`
}

type categoriesFile struct {
	Categories []string `yaml:"categories"`
}

func main() {
	dir := flag.String("dir", "marketplace", "path to the marketplace directory")
	output := flag.String("o", "", "output file (default: stdout)")
	flag.Parse()

	categoryOrder, err := loadCategoryOrder(filepath.Join(*dir, "categories.yaml"))
	if err != nil {
		fatal("%v", err)
	}

	// --- Load tools ---
	toolFiles, err := filepath.Glob(filepath.Join(*dir, "tools", "*.yaml"))
	if err != nil {
		fatal("globbing tool files: %v", err)
	}
	if len(toolFiles) == 0 {
		fatal("no tool files found in %s/tools/", *dir)
	}

	var tools []registry.ToolDef
	for _, f := range toolFiles {
		data, err := os.ReadFile(f)
		if err != nil {
			fatal("reading %s: %v", f, err)
		}
		var t registry.ToolDef
		if err := yaml.Unmarshal(data, &t); err != nil {
			fatal("parsing %s: %v", f, err)
		}
		tools = append(tools, t)
	}

	sort.SliceStable(tools, func(i, j int) bool {
		ci := categoryRank(categoryOrder, tools[i].Category)
		cj := categoryRank(categoryOrder, tools[j].Category)
		if ci != cj {
			return ci < cj
		}
		return strings.ToLower(tools[i].Name) < strings.ToLower(tools[j].Name)
	})

	// --- Load packs ---
	packFiles, err := filepath.Glob(filepath.Join(*dir, "packs", "*.yaml"))
	if err != nil {
		fatal("globbing pack files: %v", err)
	}

	var packs []packDef
	for _, f := range packFiles {
		data, err := os.ReadFile(f)
		if err != nil {
			fatal("reading %s: %v", f, err)
		}
		var p packDef
		if err := yaml.Unmarshal(data, &p); err != nil {
			fatal("parsing %s: %v", f, err)
		}
		packs = append(packs, p)
	}

	sort.SliceStable(packs, func(i, j int) bool {
		return strings.ToLower(packs[i].Name) < strings.ToLower(packs[j].Name)
	})

	// --- Assemble ---
	assembled := assembledFile{Tools: tools, Packs: packs}

	data, err := yaml.Marshal(&assembled)
	if err != nil {
		fatal("marshaling assembled marketplace: %v", err)
	}

	header := fmt.Sprintf("# clim — Tool Marketplace\n# Auto-generated from %s/tools/ and %s/packs/.\n# Do not edit this file directly — edit individual files instead.\n\n", *dir, *dir)
	content := []byte(header + string(data))

	if *output != "" {
		if err := os.WriteFile(*output, content, 0o644); err != nil {
			fatal("writing %s: %v", *output, err)
		}
		fmt.Fprintf(os.Stderr, "Assembled %d tools + %d packs → %s\n", len(tools), len(packs), *output)
	} else {
		if _, err := os.Stdout.Write(content); err != nil {
			fatal("writing to stdout: %v", err)
		}
	}
}

func loadCategoryOrder(path string) (map[string]int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading categories.yaml: %w", err)
	}
	var cf categoriesFile
	if err := yaml.Unmarshal(data, &cf); err != nil {
		return nil, fmt.Errorf("parsing categories.yaml: %w", err)
	}
	if len(cf.Categories) == 0 {
		return nil, errors.New("categories.yaml has no categories")
	}
	m := make(map[string]int, len(cf.Categories))
	for i, c := range cf.Categories {
		m[c] = i
	}
	return m, nil
}

func categoryRank(order map[string]int, cat string) int {
	if rank, ok := order[cat]; ok {
		return rank
	}
	return 999
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "error: "+format+"\n", args...)
	os.Exit(1)
}
